nginx:
  image: nginx:alpine
  volumes:
    - ./public/:/var/www/html/:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - app
  ports:
    - "4000:80"

app:
  build: .
  expose:
    - "3000"
