name: Release

on:
  push:
    tags:
      - '*@*'
      - '@*@*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - run: echo ${GITHUB_REF_NAME%@*}
